# bites-init.ps1 — scaffold .specify/bites/ on first use.

[CmdletBinding()]
param()

. "$PSScriptRoot/_lib.ps1"
Assert-BsTools -Tools @('jq','yq')

$root = Get-BsRepoRoot
$bitesDir = Get-BsBitesDir -Root $root
$extDir = Join-Path $root '.specify/extensions/byte-sized'

foreach ($sub in @('domains','_drafts','_archive')) {
    $path = Join-Path $bitesDir $sub
    if (-not (Test-Path $path)) { New-Item -ItemType Directory -Path $path | Out-Null }
}

$readme = Join-Path $bitesDir 'README.md'
if (-not (Test-Path $readme)) {
@'
# Byte-Sized Business Bites

This directory is managed by the `byte-sized` Spec Kit extension.

- `domains/<domain>/BB-*.md` — one file per active or deprecated bite.
- `_drafts/` — candidate bites awaiting human review. Not loaded by default.
- `_archive/` — superseded bites (kept for traceability).
- `index.json` — slim, agent-facing catalog. Regenerated by `byte-sized` scripts.

Do not edit `index.json` by hand. Edit the markdown files; the index will rebuild.
'@ | Set-Content -LiteralPath $readme -Encoding utf8
}

$index = Join-Path $bitesDir 'index.json'
if (-not (Test-Path $index)) {
    $ts = Get-BsNowIso
    $obj = [pscustomobject]@{ schema_version = '1.0'; generated_at = $ts; bites = @() }
    $obj | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $index -Encoding utf8
}

$tpl = Join-Path $extDir 'config-template.yml'
$cfg = Join-Path $extDir 'byte-sized-config.yml'
if ((Test-Path $tpl) -and -not (Test-Path $cfg)) {
    Copy-Item -LiteralPath $tpl -Destination $cfg
}

[pscustomobject]@{
    bites_dir     = ($bitesDir.Substring($root.Length + 1))
    extension_dir = ($extDir.Substring($root.Length + 1))
    initialized   = $true
} | ConvertTo-Json -Depth 4
