#!/usr/bin/env bash
# bites-init.sh — scaffold .specify/bites/ on first use.
#
# Creates: domains/, _drafts/, _archive/, README.md, empty index.json,
# and a project-level config file copied from the template if missing.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"

bs_require_tools jq yq

ROOT="$(bs_repo_root)"
BITES_DIR="$(bs_bites_dir "$ROOT")"
EXT_DIR="$ROOT/.specify/extensions/byte-sized"

mkdir -p "$BITES_DIR/domains" "$BITES_DIR/_drafts" "$BITES_DIR/_archive"

if [[ ! -f "$BITES_DIR/README.md" ]]; then
  cat > "$BITES_DIR/README.md" <<'EOF'
# Byte-Sized Business Bites

This directory is managed by the `byte-sized` Spec Kit extension.

- `domains/<domain>/BB-*.md` — one file per active or deprecated bite.
- `_drafts/` — candidate bites awaiting human review. Not loaded by default.
- `_archive/` — superseded bites (kept for traceability).
- `index.json` — slim, agent-facing catalog. Regenerated by `byte-sized` scripts.

Do not edit `index.json` by hand. Edit the markdown files; the index will rebuild.
EOF
fi

if [[ ! -f "$BITES_DIR/index.json" ]]; then
  ts="$(bs_now_iso)"
  jq -n --arg ts "$ts" '{schema_version: "1.0", generated_at: $ts, bites: []}' > "$BITES_DIR/index.json"
fi

# Copy config template if user hasn't created one yet.
if [[ -f "$EXT_DIR/config-template.yml" && ! -f "$EXT_DIR/byte-sized-config.yml" ]]; then
  cp "$EXT_DIR/config-template.yml" "$EXT_DIR/byte-sized-config.yml"
fi

jq -n \
  --arg bites_dir "${BITES_DIR#"$ROOT/"}" \
  --arg ext_dir "${EXT_DIR#"$ROOT/"}" \
  '{bites_dir: $bites_dir, extension_dir: $ext_dir, initialized: true}'
