#!/usr/bin/env bash
# bites-init.sh — scaffold .specify/bites/ on first use.
#
# Creates: domains/, _drafts/, _archive/, README.md, empty index.json,
# and a project-level config file copied from the template if missing.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"

bs_require_tools jq yq

ROOT="$(bs_repo_root)"
BITES_DIR="$(bs_bites_dir "$ROOT")"
EXT_DIR="$ROOT/.specify/extensions/byte-sized"

mkdir -p "$BITES_DIR/domains" "$BITES_DIR/_drafts" "$BITES_DIR/_archive"

# Pre-create the agent-scratch directory under .specify/bites/. The /baseline
# and /add command prompts direct the agent to write per-batch / per-stub YAML
# payloads here instead of the repo root; creating it up-front avoids the agent
# falling back to a root-level path because the directory didn't exist.
mkdir -p "$BITES_DIR/.tmp-byte-sized"

# Make sure the scratch folder is excluded from source control. Append a single
# entry to the project root .gitignore (creating it if missing). Idempotent:
# we only touch the file if the marker isn't already present.
ROOT_GITIGNORE="$ROOT/.gitignore"
GITIGNORE_MARKER='.tmp-byte-sized/'
if [[ ! -f "$ROOT_GITIGNORE" ]] || ! grep -Fxq "$GITIGNORE_MARKER" "$ROOT_GITIGNORE"; then
  {
    [[ -f "$ROOT_GITIGNORE" && -s "$ROOT_GITIGNORE" ]] && printf '\n'
    printf '# Added by byte-sized: agent-scratch directories created during /speckit.byte-sized.{baseline,add}.\n'
    printf '%s\n' "$GITIGNORE_MARKER"
  } >> "$ROOT_GITIGNORE"
fi

if [[ ! -f "$BITES_DIR/README.md" ]]; then
  cat > "$BITES_DIR/README.md" <<'EOF'
# Byte-Sized Business Bites

This directory is managed by the `byte-sized` Spec Kit extension.

- `domains/<domain>/BB-*.md` — one file per active or deprecated bite.
- `_drafts/` — candidate bites awaiting human review. Not loaded by default.
- `_archive/` — superseded bites (kept for traceability).
- `index.json` — slim, agent-facing catalog. Regenerated by `byte-sized` scripts.

Do not edit `index.json` by hand. Edit the markdown files; the index will rebuild.
EOF
fi

if [[ ! -f "$BITES_DIR/index.json" ]]; then
  ts="$(bs_now_iso)"
  jq -n --arg ts "$ts" '{schema_version: "1.0", generated_at: $ts, bites: []}' > "$BITES_DIR/index.json"
fi

# Copy config template if user hasn't created one yet.
if [[ -f "$EXT_DIR/config-template.yml" && ! -f "$EXT_DIR/byte-sized-config.yml" ]]; then
  cp "$EXT_DIR/config-template.yml" "$EXT_DIR/byte-sized-config.yml"
fi

jq -n \
  --arg bites_dir "${BITES_DIR#"$ROOT/"}" \
  --arg ext_dir "${EXT_DIR#"$ROOT/"}" \
  '{bites_dir: $bites_dir, extension_dir: $ext_dir, initialized: true}'
