#!/usr/bin/env bash
# rules-init.sh — scaffold .specify/rules/ on first use.
#
# Creates: domains/, _drafts/, _archive/, README.md, empty index.json,
# and a project-level config file copied from the template if missing.

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_lib.sh
source "$SCRIPT_DIR/_lib.sh"

bs_require_tools jq yq

ROOT="$(bs_repo_root)"
RULES_DIR="$(bs_rules_dir "$ROOT")"
EXT_DIR="$ROOT/.specify/extensions/byte-sized"

mkdir -p "$RULES_DIR/domains" "$RULES_DIR/_drafts" "$RULES_DIR/_archive"

if [[ ! -f "$RULES_DIR/README.md" ]]; then
  cat > "$RULES_DIR/README.md" <<'EOF'
# Byte-Sized Business Rules

This directory is managed by the `byte-sized` Spec Kit extension.

- `domains/<domain>/BR-*.md` — one file per active or deprecated rule.
- `_drafts/` — candidate rules awaiting human review. Not loaded by default.
- `_archive/` — superseded rules (kept for traceability).
- `index.json` — slim, agent-facing catalog. Regenerated by `byte-sized` scripts.

Do not edit `index.json` by hand. Edit the markdown files; the index will rebuild.
EOF
fi

if [[ ! -f "$RULES_DIR/index.json" ]]; then
  ts="$(bs_now_iso)"
  jq -n --arg ts "$ts" '{schema_version: "1.0", generated_at: $ts, rules: []}' > "$RULES_DIR/index.json"
fi

# Copy config template if user hasn't created one yet.
if [[ -f "$EXT_DIR/config-template.yml" && ! -f "$EXT_DIR/byte-sized-config.yml" ]]; then
  cp "$EXT_DIR/config-template.yml" "$EXT_DIR/byte-sized-config.yml"
fi

jq -n \
  --arg rules_dir "${RULES_DIR#"$ROOT/"}" \
  --arg ext_dir "${EXT_DIR#"$ROOT/"}" \
  '{rules_dir: $rules_dir, extension_dir: $ext_dir, initialized: true}'
